import {action} from 'easy-peasy';

export const form ={
   nome : '',
   pagina1: '',
   pagina2: '',
   pagina3: '',
   pagina4: '',
   pagina5: '',
   pagina6: '',
   pagina7: '',
   pagina8: '',
   pagina9: '',
   pagina10: '',
   pagina11: '',
   pagina12: '',
   pagina13: '',
   pagina14: '',
   pagina15: '',
   pagina16: '',
   pagina17: '',
   pagina18: '',
   pagina19: '',
   pagina20: '',
   pagina21: '',
   pagina22: '',
   pagina23: '',
   pagina24: '',
   pagina25: '',
   pagina26: '',
   pagina27: '',
   pagina28: '',
   pagina29: '',
   pagina30: '',
   LID : [] ,
    PD : [],
    IE : [],
    TD : [],
    CM : [],
    CA : [],

   
   setForm: action((state,payload)=>{state = payload}),
}